### ISSUE TITLE
Is Helga overpowered w/ Flamebolt?

### ISSUE THREAD

**Issue by ChitownWillie** [Skitia/Helga-BG1#4]
Just double-checking if the THAC0 settings are right - That's scary powerful for Level 1!

![image](https://user-images.githubusercontent.com/65503897/165798642-59f04a99-7fd4-4875-a632-2b64b44fad72.png)

Note: The "Two-Handed Style: 1" comes from Scales of Balance's "Fighting Style Overhaul", which grants +1 thac0.

**Comment by Skitia** [comment]
The THACO is one stronger than it is in my local game (Flamebolt should be
-3, not -4), but it's close to accurate. It's countered by the fact it only
lasts one turn (It used to also prevent spellcasting, but another player
complained it was too limiting). It's designed to be used for tougher
fights, where the one turn limit of the sword can be more fully utilized.

If I did any further weakening, it would be to make it staggered, +1 at
level 1, +2 at level 5, +3 at level 10, +4 at level 15, and +5 at level 20
rather than a flat +3. (It used to be that way, but again, a player claimed
it was too weak for a short duration weapon spell)

**Comment by ChitownWillie** [comment]
Gotcha - Understood.

Perhaps something in the middle, such as:

   - No spellcasting *except* for Cure spells, and
   - More aggressive staggering, such as +1 Level 1, +2 Level 3, +3 Level 6
   (to mirror Warrior weapon proficiency and a nod to her warrior kin)

Just thinking out loud.

Nonetheless, looking forward to trying her out. Thanks for your hard work!
